ethereum_rpc = "https://rpc.hoodi.ethpandaops.io"
drosera_rpc  = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps.treasury_drain_monitor]
path = "out/TreasuryTrap.sol/TreasuryTrap.json"
response_contract = "0xfFcacf4e403E5d053459373e79ffE5f92aE720c6"
response_function = "alertTreasuryDrain(uint256,uint256,string)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 1
private_trap = true
whitelist = ["0x38c9643b4ac28892DE25De176B724D065dfbbaB3"]
gas_limit = 500000
address = "0xe04d0c303f6E48e44c2Dac3E4Db4D00E237093E3"
